# Generated by Django 2.2 on 2019-04-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='UserProfile',
        ),
    ]
