# Generated by Django 2.2 on 2019-04-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_auto_20190414_1320'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='verifycode',
            table='VerifyCode',
        ),
    ]
